---
- name: Combine all certification tags, tests and programs
  set_fact:
    all_certification_types: '{{ openstack_certification_tags }} + {{ openstack_certification_tests }} + {{ openstack_certification_programs }}'

- block:
    - name: Register keystone_auth_url
      shell: "source /etc/redhat-certification-openstack/overcloudrc && echo \"$OS_AUTH_URL\""
      register: keystone_auth_url

    - name: Register admin_username
      shell: "source /etc/redhat-certification-openstack/overcloudrc && echo \"$OS_USERNAME\""
      register: admin_username

    - name: Register admin_password
      shell: "source /etc/redhat-certification-openstack/overcloudrc && echo \"$OS_PASSWORD\""
      register: admin_password

    - name: Register admin_tenant_name
      shell: "source /etc/redhat-certification-openstack/overcloudrc && echo \"$OS_TENANT_NAME\""
      register: admin_tenant_name

    - name: Register admin_project_name
      shell: "source /etc/redhat-certification-openstack/overcloudrc && echo \"$OS_PROJECT_NAME\""
      register: admin_project_name

    - name: Create the test_config.json file
      become: True
      template:
        src: test_config.json.j2
        dest: /etc/redhat-certification-openstack/test_config.json
  when: "'baremetal' not in all_certification_types"

- name: Create the baremetal.json file
  become: True
  template:
    src: baremetal.json
    dest: /etc/redhat-certification-openstack/baremetal.json
  when: "'undercloud' in group_names and 'baremetal' in all_certification_types"

- name: Run certification test suite with tag argument
  become: True
  shell: >
    set -x
    rhcert-ci clean all && rhcert-ci run --tag {{ item }} && rhcert-ci save
  with_items: "{{ openstack_certification_tags }}"
  ignore_errors: True
  when: openstack_certification_test_type == "tag"

- name: Run certification test suite with program argument
  become: True
  shell: >
    set -x
    rhcert-ci clean all && rhcert-ci run --program {{ item }} && rhcert-ci save
  with_items: "{{ openstack_certification_programs }}"
  ignore_errors: True
  when: openstack_certification_test_type == "program"

- name: Run certification test suite with test argument
  become: True
  shell: >
    set -x
    rhcert-ci clean all && rhcert-ci run --test {{" --test ".join(openstack_certification_tests)}} && rhcert-ci save
  ignore_errors: True
  when: openstack_certification_test_type != "tag" and openstack_certification_test_type != "program"

