---
# This file and plugin.spec are required by Infrared project

- hosts: undercloud
  remote_user: stack
  become: yes
  roles:
    - ansible-role-openstack-certification

  pre_tasks:
    - name: Set openstack_certification_output_format
      set_fact:
        openstack_certification_output_format: "{{ test.openstack_certification_output_format }}"
      when: test.openstack_certification_output_format

    - name: Set openstack_certification_results_download
      set_fact:
        openstack_certification_results_download: true
      when: test.openstack_certification_results_download

    - name: Set openstack_certification_output_filename
      set_fact:
        openstack_certification_output_filename: "{{ test.openstack_certification_output_filename }}"
      when: test.openstack_certification_output_filename

    - name: Set openstack_certification_test_type
      set_fact:
        openstack_certification_test_type: "{{ test.openstack_certification_test_type }}"
      when: test.openstack_certification_test_type

    - name: Set openstack_certification_tests
      set_fact:
        openstack_certification_tests: "{{ test.openstack_certification_tests }}"
      when: test.openstack_certification_tests

    - name: Set openstack_certification_tags
      set_fact:
        openstack_certification_tags: "{{ test.openstack_certification_tags }}"
      when: test.openstack_certification_tags is defined

    - name: Set openstack_certification_programs
      set_fact:
        openstack_certification_programs: "{{ test.openstack_certification_programs }}"
      when: test.openstack_certification_programs is defined

    - name: Set openstack_certification_supported_apis_and_extensions
      set_fact:
        openstack_certification_supported_apis_and_extensions: "{{ test.openstack_certification_supported_apis_and_extensions }}"
      when: test.openstack_certification_supported_apis_and_extensions is defined

    - name: Set openstack_certification_enable_rhsm_repo
      set_fact:
        openstack_certification_enable_rhsm_repo: false
      when: not test.openstack_certification_enable_rhsm_repo

    - name: Set openstack_certification_repo_file
      set_fact:
        openstack_certification_repo_file: "{{ test.openstack_certification_repo_file }}"
      when: test.openstack_certification_repo_file is defined

    - name: Set openstack_certification_tempest_conf_path
      set_fact:
        openstack_certification_tempest_conf_path: "{{ test.openstack_certification_tempest_conf_path }}"
      when: test.openstack_certification_tempest_conf_path is defined
