{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.image in ["centos:7"] %}
RUN yum install -y sudo libselinux-python && yum clean all
{% else %}
RUN yum install -y sudo python3-libselinux && yum clean all
{% endif %}

RUN adduser centos && \
    echo 'centos ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/90-centos && \
    chmod 440 /etc/sudoers.d/90-centos
