---
dependency:
  name: galaxy
  enabled: false

driver:
  name: podman

platforms:
  - name: el7
    image: quay.io/centos/centos:7
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
  - name: el8
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    capabilities:
      - SYS_ADMIN

lint: yamllint tasks

provisioner:
  name: ansible
  log: true
  connection_options:
    ansible_user: centos
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - syntax

verifier:
  name: testinfra
  lint:
    name: flake8
